# --------------------
# Define arguments.
# --------------------

# ==================== Alas ====================

Scheduler:
  Enable:
    type: checkbox
    value: false
    option: [ true, false ]
  NextRun: 2020-01-01 00:00:00
  Command: Alas
  ServerUpdate:
    value: "00:00"
    display: hide
Error:
  Restart:
    value: game
    option: [ game, game_emulator ]
  SaveError: true
  ScreenshotLength: 1
  OnePushConfig:
    type: textarea
    mode: yaml
    value: 'provider: null'
Optimization:
  ScreenshotInterval: 0.3
  CombatScreenshotInterval: 1.0
  WhenTaskQueueEmpty:
    value: stay_there
    option: [ stay_there, goto_main, close_game ]
  MaxConcurrentInstance: 3
Playwright:
  Browser:
    type: select
    value: msedge
    option:
      - msedge
      - chrome
  Headless: false
  CleanPagesOnStart: false
  AutoOpenDevtools: false
  RemoteDebuggingAddress: "127.0.0.1:9222"
  LaunchDedicatedBrowser: false
  AutoAcceptDialog: true
  UseDefaultProfile: false
  CustomUserAgent: ''
  ExtensionDirectory: "$LOCALAPPDATA/Microsoft/Edge/User Data/Default/Extensions"
  ExtensionNames:
    type: textarea
    value: |
      Ruffle
      AdGuard
  ExtraChromiumArgs:
    type: textarea
    value: |
      --disable-features=IsolateOrigins,site-per-process
      --disable-infobars
      --window-size=1280,800
ProfileSettings:
  MinNpKeep: 100000
  JellyNeoExpiry: 168
  TaskSoftTerminationTime: 5

# ==================== Chore ====================
NeopianBank:
  DepositThreshold: 1000000
  MaxDeposit: 500000
PetCares:
  FeedBlacklist:
    type: textarea
    value: |
      poison
      rotten
      dung
      glowing
      clay
      smelly
  PlayBlackList:
    type: textarea
    value: ""
  GroomBlackList:
    type: textarea
    value: ""
  MaxFeedValue: 1000
  MaxFeedLevel:
    type: select
    value: "full up"
    option:
      - "dying"
      - "starving"
      - "famished"
      - "very hungry"
      - "hungry"
      - "not hungry"
      - "fine"
      - "satiated"
      - "full up"
      - "very full"
      - "bloated"
DailyQuest:
  PurchaseCheapItems: false
Restocking:
  ActiveRestocking: false
  ActiveRestockInterval: 60
  EnableCaptchaDebug: false
  RestockPerShop: 5
  MinProfit: 1000
  MaxShopStock: 5
  MaxCost: 1000000
  ImmediateProfit: 3500
  ShopList:
    type: textarea
    value: "1,2,3,5,10,14,15,16,20,25,34,35,39,40,42,44,46,50,56,57,61,80,81,95,97,101,103"
  BargainStrategyScript:
    type: textarea
    value: |
      # purposes: list of shopkeeper's purposes
      # offers: list of your offers
      # depth: number of bargains made
      purposed = purposes[-1]
      last_offer = offers[-1] if offers else 0
      if purposed > 100000 or depth > 5:
        return purposed
      if len(purposes) > 2 and purposes[-2] == purposes[-3]:
        return purposed
      if last_offer == 0:
        return int(purposed * 0.4 // 10 * 10)
      delta = purposed - last_offer
      step  = 20
      if delta > 3000:
        step = 1000
      elif delta > 1500:
        step = 500
      elif delta > 300:
        step = 100
      elif delta > 150:
        step = 50
      ret = max(1, min(purposed, last_offer + int(delta * 0.4 // step * step)))
      if ret == last_offer:
          ret = int(purposed // 10 * 10)
      return ret
QuickStock:
  KeepInventorySlot: 5
  DepositValue: 100000
  RestockProfit: 1000
  WithdrawTill: true
  CategoryKeeps:
    type: textarea
    value: |
      food:10
      grooming: 1
      toy: 1
  PriceStrategyScript:
    type: textarea
    value: |
      mkp = item['market_price']
      if mkp < 10000:
          return mkp * 0.99
      return mkp
  ForceDepositList:
    type: textarea
    value: |
      Basic Gift Box
  DepositBlacklist:
    type: textarea
    value: ""
  DonateNameList:
    type: textarea
    value: |
      Old Rotten Right Sandal
      Old Rotten Left Sandal
      Old Rotten Right Boot
      Old Rotten Left Boot
      Old Rotten Right Shoe
      Old Rotten Left Shoe

HealingSpring:
  Interval: 30

StockMarket:
  SellProfitRatio: 20

ShopWizard:
  EnableActivePriceUpdate: false
  PriceUpdateInterval: 30
  PriceUpdateBatchSize: 10
  PriceUpdateRescans: 5
  ShopWizardRequests:
      stored: StoredShopWizardRequests
      display: true

PetTraining:
  BuyFeeFromPlayers: false
  TrainPriority: "str > def > hp > mov > lv"
  Config:
    type: textarea
    value: |
      PetName:Academy:TargetLv:TargetStr:TargetDef:TargetMov:TargetHp
  PendingTrainingFee:
    stored: StoredPendingTrainingFee
    display: true

VoidsWithin:
  DelayForDailyFeed: true
  AvailablePetsCount: 0
  DispatchBlacklist:
    type: textarea
    value: ""
  EarnedPlotPoints:
    stored: StoredInt
    display: true
    order: 4

PlayerStorage:
  NeoPoints:
    stored: StoredInt
    display: true
    order: 1
    color: "#FFD700"
  DailyQuestRestockTimesLeft:
    stored: StoredDailyQuestRestockCounter
    display: true
  DailyQuestFeedTimesLeft:
    stored: StoredDailyQuestFeedCounter
    display: true
  InventoryData:
    stored: StoredItemContainer
    display: true
    order: 2
    color: "#6DA9E4"
  StockData:
    stored: StoredItemContainer
    display: true
    order: 3
    color: "#E4B86D"
  PetsData:
    stored: StoredPetsData

SafetyDepositBox:
  DepositData:
      stored: StoredItemContainer
      display: true

# ==================== Games ====================
