# --------------------
# Define default values
# --------------------

# ==================== Alas ====================

# ==================== Daily ====================

# ==================== Weekly ====================
