from collections import defaultdict
from email.policy import default

HUNGER_LEVEL = defaultdict(lambda: 10, {
    "dying": 0,
    "starving": 1,
    "famished": 2,
    "very hungry": 3,
    "hungry": 4,
    "not hungry": 5,
    "fine": 6,
    "satiated": 7,
    "full up": 8,
    "very full": 9,
    "bloated": 10,
    "very bloated": 11,
})
HUNGER_VALUE = {v: k for k, v in HUNGER_LEVEL.items()}

SHOP_NAME = defaultdict(lambda: "", {
    1: "fresh_foods",
    2: "magic_shop",
    3: "toy_shop",
    4: "unis_clothing_shop",
    5: "grooming_parlour",
    7: "magical_bookshop",
    8: "collectable_card_shop",
    9: "battle_magic",
    10: "defence_magic",
    12: "neopian_garden_centre",
    14: "chocolate_factory",
    15: "the_bakery",
    16: "smoothie_shop",
    20: "tropical_food",
    25: "neopian_petpet_shop",
    34: "coffee_cave",
    35: "slushie_shop",
    39: "faerie_foods",
    40: "faerieland_petpets",
    41: "neopian_furniture",
    42: "tyrannian_foods",
    44: "tyrannian_petpets",
    46: "huberts_hotdogs",
    50: "peopatra_petpets",
    55: "osiris_pottery",
    56: "merifoods",
    57: "ye_olde_petpets",
    61: "wintery_petpets",
    80: "brightvale_armoury",
    81: "brightvale_fruits",
    95: "exquisite_ambrosia",
    97: "legendary_petpets",
    101: "exotic_foods",
    103: "fanciful_fauna"
})

BANK_LEVEL_NAME = defaultdict(lambda: 0, {
    0: "Junior Saver",
    1: "Neopian Student",
    2: "Bronze Saver",
    3: "Silver Saver",
    4: "Super Gold Plus",
    5: "Platinum Extra",
    6: "Double Platinum",
    7: "Triple Platinum",
    8: "Diamond Deposit",
    9: "Diamond Deposit Plus",
    10: "Diamond Deposit Gold",
    11: "Millionaire Platinum",
    12: "Millionaire Double Platinum",
    13: "Millionaire Mega-Platinum",
    14: "Neopian Mega-Riches",
    15: "Ultimate Riches!",
    16: "Whitehouse"
})

BANK_LEVEL_REQUIREMENT = defaultdict(lambda: 0, {
    0: 0,
    1: 1_000,
    2: 2_500,
    3: 5_000,
    4: 10_000,
    5: 25_000,
    6: 50_000,
    7: 75_000,
    8: 100_000,
    9: 250_000,
    10: 500_000,
    11: 1_000_000,
    12: 2_000_000,
    13: 5_000_000,
    14: 7_500_000,
    15: 10_000_000,
    16: 2**63 - 1
})