import datetime

# This file was automatically generated by module/config/config_updater.py.
# Don't modify it manually.


class GeneratedConfig:
    """
    Auto generated configuration
    """

    # Group `Scheduler`
    Scheduler_Enable = False  # True, False
    Scheduler_NextRun = datetime.datetime(2020, 1, 1, 0, 0)
    Scheduler_Command = 'Alas'
    Scheduler_ServerUpdate = '00:00'

    # Group `Error`
    Error_Restart = 'game'  # game, game_emulator
    Error_SaveError = True
    Error_ScreenshotLength = 1
    Error_OnePushConfig = 'provider: null'

    # Group `Optimization`
    Optimization_ScreenshotInterval = 0.3
    Optimization_CombatScreenshotInterval = 1.0
    Optimization_WhenTaskQueueEmpty = 'goto_main'  # stay_there, goto_main, close_game

    # Group `Playwright`
    Playwright_Browser = 'msedge'  # msedge, msedge-beta, msedge-dev, msedge-canary, chrome, chrome-beta, chrome-dev, chrome-canary
    Playwright_Headless = False
    Playwright_AutoOpenDevtools = False
    Playwright_AutoAcceptDialog = True
    Playwright_ExtensionDirectory = '$LOCALAPPDATA/Microsoft/Edge/User Data/Default/Extensions'
    Playwright_ExtensionNames = 'Ruffle'
    Playwright_ExtraChromiumArgs = '--disable-blink-features=AutomationControlled\n--disable-features=IsolateOrigins,site-per-process\n--disable-infobars\n'

    # Group `ProfileSettings`
    ProfileSettings_MinNpKeep = 20000
    ProfileSettings_JellyNeoExpiry = 168
    ProfileSettings_DataStorage = 'local'  # local, redis
    ProfileSettings_TaskSoftTerminationTime = 5

    # Group `NeopianBank`
    NeopianBank_DepositThreshold = 1000000
    NeopianBank_MaxDeposit = 500000

    # Group `PetCares`
    PetCares_FeedBlacklist = 'poison\nrotten\ndung\nglowing\nclay\nsmelly\n'
    PetCares_PlayBlackList = None
    PetCares_GroomBlackList = None
    PetCares_MaxFeedValue = 1000
    PetCares_MaxFeedLevel = 'full up'  # dying, starving, famished, very hungry, hungry, not hungry, fine, satiated, full up, very full, bloated
